# Generated by Django 5.1.7 on 2025-06-08 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.PositiveIntegerField(default=60, help_text='Default duration for a reservation slot in minutes.')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_smoking', models.BooleanField(default=False)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_types', to='restaurants.restaurantsetup')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='restaurants.restaurantsetup')),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='restaurants.tabletype')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('table_type', 'date', 'time')},
            },
        ),
    ]
