# Generated by Django 5.1.7 on 2025-06-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletype',
            options={'verbose_name': 'Table Type', 'verbose_name_plural': 'Table Types'},
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='is_smoking',
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='tabletype',
            name='name',
            field=models.CharField(default='a', help_text="A descriptive name for this table type (e.g., '2-person table', '4-person booth').", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabletype',
            name='capacity',
            field=models.PositiveIntegerField(default=2, help_text='The maximum number of guests this type of table can accomodate'),
        ),
        migrations.AlterField(
            model_name='tabletype',
            name='setup',
            field=models.ForeignKey(help_text='The restaurant setup this table type belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_types', to='restaurants.restaurantsetup'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_smoking', models.BooleanField(default=False, help_text='Is smoking allowed on this table')),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('shape', models.CharField(choices=[('RECTANGLE', 'Rectangle'), ('CIRCLE', 'Circle')], default='RECTANGLE', help_text='The shape this table has on canvas', max_length=10)),
                ('setup', models.ForeignKey(help_text='The restaurant setup this table belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurantsetup')),
                ('table_type', models.ForeignKey(help_text='The table type this table belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.tabletype')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'unique_together': {('setup', 'name')},
            },
        ),
    ]
