# Generated by Django 5.1.7 on 2025-05-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, to='restaurants.ownerprofile'),
        ),
    ]
