# Generated by Django 5.1.7 on 2025-05-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ownerprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
