# Generated by Django 5.1.7 on 2025-06-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_tabletype_options_remove_tabletype_is_smoking_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tabletype',
            unique_together={('setup', 'name')},
        ),
    ]
