# Generated by Django 5.1.7 on 2025-05-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_ownerprofile_id_alter_ownerprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RestaurantSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tables', models.IntegerField(default=0)),
                ('num_tables_smoking', models.IntegerField(default=0)),
                ('timeslots_by_day', models.JSONField(default=dict)),
                ('tables_by_size', models.JSONField(default=dict)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_setup', to='restaurants.restaurant')),
            ],
        ),
    ]
