# Generated by Django 5.1.7 on 2025-06-09 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_time_slot'),
        ('restaurants', '0003_alter_tabletype_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='The day of the week this table belongs to.')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='restaurants.restaurantsetup')),
            ],
            options={
                'verbose_name': 'Operating Hour',
                'verbose_name_plural': 'Operating Hours',
                'ordering': ['day_of_week', 'open_time'],
                'unique_together': {('setup', 'day_of_week', 'open_time', 'close_time')},
            },
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
