# Generated by Django 5.1.7 on 2025-06-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_validated_restaurantsetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsetup',
            name='num_tables_smoking',
        ),
    ]
