# Generated by Django 5.1.7 on 2025-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_operationhours_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='radius',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='x_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_position',
            field=models.FloatField(),
        ),
    ]
