# Generated by Django 5.1.7 on 2025-06-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('description', models.CharField(max_length=300)),
                ('setup', models.ForeignKey(help_text='The restaurant setup this Special Day belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='special_day', to='restaurants.restaurantsetup')),
            ],
        ),
    ]
