# Generated by Django 5.1.7 on 2025-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('number_of_people', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('BLOCKED', 'blocked')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
