# Generated by Django 5.1.7 on 2025-06-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slot',
        ),
    ]
